"""add text and status columns

Revision ID: c3abfd4a4242
Revises: d65dc91a5d2a
Create Date: 2026-05-09 08:08:21.601215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3abfd4a4242'
down_revision: Union[str, Sequence[str], None] = 'd65dc91a5d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'status')
    op.drop_column('files', 'text')
    # ### end Alembic commands ###
